# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-16 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.IntegerField(default=0, verbose_name='父级权限')),
                ('right_name', models.CharField(default='', max_length=20, verbose_name='权限名称')),
            ],
            options={
                'verbose_name': '权限表',
                'verbose_name_plural': '权限表',
            },
        ),
        migrations.CreateModel(
            name='TRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(max_length=20, verbose_name='角色名称')),
                ('parent_role', models.IntegerField(default=0, verbose_name='父级角色')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('description', models.CharField(default='', max_length=200, verbose_name='角色描述')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.TRight', verbose_name='权限')),
            ],
            options={
                'verbose_name': '角色表',
                'verbose_name_plural': '角色表',
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('password', models.CharField(max_length=64, verbose_name='登录密码')),
                ('vername', models.CharField(max_length=64, verbose_name='用户姓名')),
                ('count', models.IntegerField(default=0, verbose_name='登录次数')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now_add=True, verbose_name='上次登录时间')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
        ),
    ]
