# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-18 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191116_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
    ]
