# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-18 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_tuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='count',
            field=models.IntegerField(default=0, verbose_name='登录次数'),
        ),
    ]
