# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-18 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_tuser_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trole',
            old_name='login_name',
            new_name='name',
        ),
    ]
