# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-18 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191118_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.TRole', verbose_name='角色'),
            preserve_default=False,
        ),
    ]
