# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-18 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_tuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuser',
            name='role',
        ),
    ]
