# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-18 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict_con', '0012_auto_20191118_1857'),
        ('users', '0008_tuser_trole'),
    ]

    operations = [
        migrations.AddField(
            model_name='tright',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='tright',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序号'),
        ),
        migrations.AddField(
            model_name='tright',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dict_con.BaseType', verbose_name='类型'),
        ),
    ]
