# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-18 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191118_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='tright',
            name='link',
            field=models.CharField(default='', max_length=150, verbose_name='路径'),
        ),
    ]
