# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-19 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_tright_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tright',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='tright',
            name='link',
            field=models.CharField(default='', max_length=150, verbose_name='链接'),
        ),
    ]
