# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-19 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191119_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='tright',
            name='sign',
            field=models.CharField(default='', max_length=200, verbose_name='签名'),
        ),
    ]
