# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-19 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_tright_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tright',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='序号'),
        ),
    ]
