# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-19 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_tright_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tright',
            name='sort',
            field=models.IntegerField(default=20, verbose_name='序号'),
        ),
    ]
