# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-19 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20191119_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tright',
            name='sort',
        ),
    ]
