# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-20 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_tright_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='tright',
            name='params',
            field=models.CharField(default='', max_length=200, verbose_name='参数'),
        ),
    ]
