# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-21 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_tright_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
            ],
        ),
        migrations.RemoveField(
            model_name='tright',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tright',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='trole',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='trole',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tuser',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='tuser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tuser',
            name='is_active',
        ),
        migrations.AddField(
            model_name='tright',
            name='base_model_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Base_Model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trole',
            name='base_model_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Base_Model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tuser',
            name='base_model_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Base_Model'),
            preserve_default=False,
        ),
    ]
