# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-08 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30, verbose_name='类型名称')),
                ('parent_type', models.IntegerField(default=0, verbose_name='父级类型关系')),
                ('parent_class_type', models.IntegerField(default=0, verbose_name='类型')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '类型配置表',
                'verbose_name_plural': '类型配置表',
            },
        ),
    ]
