# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-08 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict_con', '0003_remove_baseclass_updated_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseclass',
            options={'verbose_name': '字典类型表', 'verbose_name_plural': '字典类型表'},
        ),
        migrations.AddField(
            model_name='basetype',
            name='order',
            field=models.IntegerField(default=0, verbose_name='顺序'),
        ),
    ]
