# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-12 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict_con', '0008_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='area',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='area',
            field=models.IntegerField(default=None, verbose_name='面积'),
            preserve_default=False,
        ),
    ]
