# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-15 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict_con', '0010_auto_20191115_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
