# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-21 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='BaseType',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_dict.BaseModel')),
                ('name', models.CharField(max_length=30, verbose_name='类型名称')),
                ('pid', models.IntegerField(default=-1, verbose_name='父级类型')),
            ],
            options={
                'verbose_name': '字典类型表',
                'verbose_name_plural': '字典类型表',
            },
            bases=('base_dict.basemodel',),
        ),
    ]
