# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-21 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_dict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetype',
            name='pid',
            field=models.IntegerField(verbose_name='父级类型'),
        ),
    ]
