# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-21 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_dict', '0002_auto_20191121_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_dict.BaseModel')),
                ('pid', models.IntegerField(default=0, verbose_name='父级权限')),
                ('name', models.CharField(default='', max_length=20, verbose_name='权限名称')),
                ('order', models.IntegerField(default=0, verbose_name='排序号')),
                ('link', models.CharField(default='', max_length=150, verbose_name='链接')),
                ('params', models.CharField(default='', max_length=200, verbose_name='参数')),
                ('sign', models.CharField(default='', max_length=200, verbose_name='签名')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_dict.BaseType', verbose_name='类型')),
            ],
            options={
                'verbose_name': '权限表',
                'verbose_name_plural': '权限表',
            },
            bases=('base_dict.basemodel',),
        ),
    ]
