# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-22 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_dict', '0003_jurisdiction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_dict.BaseModel')),
                ('name', models.CharField(max_length=30, verbose_name='角色名称')),
                ('role', models.CharField(default='', max_length=200, verbose_name='拥有权限')),
                ('description', models.CharField(default='', max_length=200, verbose_name='角色描述')),
            ],
            options={
                'verbose_name': '角色表',
                'verbose_name_plural': '角色表',
            },
            bases=('base_dict.basemodel',),
        ),
    ]
