# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-22 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_dict', '0005_auto_20191122_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='description',
        ),
    ]
