# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-22 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_dict', '0006_remove_roles_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_dict.BaseModel')),
                ('name', models.CharField(max_length=30, verbose_name='登录名')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('vname', models.CharField(max_length=30, verbose_name='用户名')),
                ('rolesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_dict.Roles', verbose_name='角色')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
            bases=('base_dict.basemodel',),
        ),
    ]
