# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-22 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_dict', '0007_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=128, verbose_name='密码'),
        ),
    ]
