# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-22 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_dict', '0008_auto_20191122_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='password',
            new_name='passwords',
        ),
    ]
