# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-08 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict_con', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30, verbose_name='类型名称')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '总体分类表',
                'verbose_name_plural': '总体分类表',
            },
        ),
        migrations.AlterField(
            model_name='basetype',
            name='parent_class_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict_con.BaseClass', verbose_name='从属'),
        ),
        migrations.AlterField(
            model_name='basetype',
            name='parent_type',
            field=models.IntegerField(default=0, verbose_name='父级类型'),
        ),
    ]
