# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-11 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict_con', '0004_auto_20191108_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetype',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序号'),
        ),
    ]
