# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-11 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict_con', '0005_auto_20191111_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='测试')),
            ],
        ),
    ]
