# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-18 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict_con', '0011_auto_20191115_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basetype',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='basetype',
            name='order',
        ),
    ]
