# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-21 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict_con', '0012_auto_20191118_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basetype',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='basetype',
            name='updated_time',
        ),
    ]
